name: "Publish"

env:
  ADDON_NAME: ipfs-daemon

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ${{ env.ADDON_NAME }} \
            --docker-hub ghcr.io/patara43 \
            --image ${{ env.ADDON_NAME }}-{arch} 
